[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32"
ESP_IDF_VERSION = "v5.2.2"
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults", relative = true }
IDF_PYTHON_CHECK_CONSTRAINTS = "no"
ESP_IDF_COMPONENT_MANAGER = "off"
LD_LIBRARY_PATH = { value = ".embuild/lib", relative = true }
